# Brownie ethPM package configuration file

package_name: ticket-snek
version: 0.1.0-alpha.1

meta:
  description: Ticketmaster, but on the blockchain
  authors:
    - @fubuloubu
  license: MIT
  keywords:
    - Tickets
    - Sneks
  links:
    website:
    documentation:
    repository:
    audit:
